### ISSUE TITLE
Bug-report: Install from Repository fails on Debian 11(.6) Linux Container (LXC)

### ISSUE THREAD

**Issue by hiatsu0** [tmiland/invidious-updater#100]
My preferred method of installation seems to fail in Debian 11 container (LXC) running on Proxmox host due to unsupported package compression method.

**To Reproduce**
1. Follow the Repository instructions at: https://github.com/tmiland/invidious-updater#repository
2. (`sudo`, `curl` and `gpg` need to be installed separately, as those are not included in default container image)
3. Repo update succeeds, but installation fails on error with `unknown compression`:

```
# apt install invidious-updater
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  invidious-updater
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 992 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://deb.tmiland.com/debian ./ invidious-updater 2.1.0 [992 B]
Fetched 992 B in 0s (3295 B/s)            
dpkg-deb: error: archive '/var/cache/apt/archives/invidious-updater_2.1.0_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/invidious-updater_2.1.0_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/invidious-updater_2.1.0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Underlying issue seems to be `dpkg` being <1.21.18 which is indeed the case in my container, with `dpkg --version` showing 1.20.12. (https://unix.stackexchange.com/a/669008/523204)
'
'
'

**Additional context** (Unrelated to repository installation above):

Also tested the direct installation method `curl -sSL | bash` but this seems to hang before text "_Select an option [1-10]:_" even appears. It gave also an error about missing `lsb_release` command which was easy to fix by `apt install lsb_release` but the script still hangs.

Third provided method of installation  (`wget && chmod +x && ./invidious_update.sh`) seemed to get everything compiled without errors, and the service is running, but for some reason there is no reply from http://localhost:3000. (will see if I simply did/understood something wrong, or if there is something in logs -- will post another issue if so)

Or I maybe I'll try docker next.

**Comment by tmiland** [comment]
Hello,
sorry for the inconvenience. Please do an `apt update` and try latest version.

Just pushed [an update](https://github.com/tmiland/deb.tmiland.com/commit/f1c73b943198684bb26a876d67a728dd7b0eb8c6) to the repo which should fix the issue you are experiencing.

**Comment by hiatsu0** [comment]
Can confirm that the .deb does install now on Debian 11.

(still unable to get anything to appear on port 3000 after installation but that must be either my bad or some compatibility issue with the LXC in Proxmox, like `unprivileged` setting, or something else altogether)
